In [5]:
import numpy as np
import os

world = 0
print("cwd", os.getcwd())
print(np.load("./jackal-map-creation/test_data/cspace_files/cspace_" + str(world) + ".npy").shape)
print(np.load("./jackal-map-creation/test_data/grid_files/grid_" + str(world) + ".npy").shape)

counts = []
for i in range(300):
  f = np.load("./jackal-map-creation/test_data/grid_files/grid_" + str(i) + ".npy")
  print(i, f.shape, f.sum(), "boxes=", f.sum() - (2 * f.shape[0]))
  counts.append(f.sum())

print("min", min(counts))

cwd /home/robert/nomad_thesis/tools
(15, 15)
(15, 15)
0 (15, 15) 33 boxes= 3
1 (15, 15) 44 boxes= 14
2 (15, 15) 42 boxes= 12
3 (15, 15) 36 boxes= 6
4 (15, 15) 39 boxes= 9
5 (15, 15) 46 boxes= 16
6 (15, 15) 52 boxes= 22
7 (15, 15) 42 boxes= 12
8 (15, 15) 46 boxes= 16
9 (15, 15) 42 boxes= 12
10 (15, 15) 45 boxes= 15
11 (15, 15) 43 boxes= 13
12 (15, 15) 47 boxes= 17
13 (15, 15) 43 boxes= 13
14 (15, 15) 40 boxes= 10
15 (15, 15) 46 boxes= 16
16 (15, 15) 48 boxes= 18
17 (15, 15) 47 boxes= 17
18 (15, 15) 42 boxes= 12
19 (15, 15) 49 boxes= 19
20 (15, 15) 45 boxes= 15
21 (15, 15) 55 boxes= 25
22 (15, 15) 41 boxes= 11
23 (15, 15) 51 boxes= 21
24 (15, 15) 36 boxes= 6
25 (15, 15) 45 boxes= 15
26 (15, 15) 46 boxes= 16
27 (15, 15) 40 boxes= 10
28 (15, 15) 46 boxes= 16
29 (15, 15) 39 boxes= 9
30 (15, 15) 42 boxes= 12
31 (15, 15) 36 boxes= 6
32 (15, 15) 33 boxes= 3
33 (15, 15) 44 boxes= 14
34 (15, 15) 38 boxes= 8
35 (15, 15) 55 boxes= 25
36 (15, 15) 43 boxes= 13
37 (15, 15) 42 boxes= 12
38 (15, 15) 47

In [14]:
print(np.load("./jackal-map-creation/test_data/grid_files/grid_" + str(2) + ".npy"))
print(np.load("./jackal-map-creation/test_data/grid_files/grid_" + str(world) + ".npy").sum())

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [13]:
print(np.load("./jackal-map-creation/test_data/cspace_files/cspace_" + str(2) + ".npy"))

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 0]
 [0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 0]
 [0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 0]
 [0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 0 0]
 [0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 0 0]
 [0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0